@startuml
skinparam defaultTextAlignment left
[*] --> App
state App{
state WaitForM1{

WaitForM1 --> WaitForM2 : e:app?m1\nid = e.a

}
state WaitForM2{

WaitForM2 --> SendAck : e:app?m2
}
state SendAck{
	SendAck : entry / do\n  app!m3(id)


SendAck --> WaitForM1
}
[*] --> WaitForM1
}
@enduml
