@startuml
BreakoutGame -> HeadlessDisplay1: <b>  setColor(107, 94, 174)</b>\n  [0x01, <font color="red"><i>0x6B</i></font>, <font color="green"><i>0x5E</i></font>, <font color="blue"><i>0xAE</i></font>]
BreakoutGame -> HeadlessDisplay2: <b>  setColor(107, 94, 174)</b>\n  [0x01, <font color="blue"><i>0xAE</i></font>, <font color="green"><i>0x5E</i></font>, <font color="red"><i>0x6B</i></font>]
@enduml