@startuml
note over BreakoutGame, HeadlessDisplay: INIT.on_entry
BreakoutGame -> HeadlessDisplay: <b>createxsize(8, <font color="blue"><u>160</u></font>)</b>\n[<font color="red"><i>0x03</i></font>, 0x08, <font color="blue"><u>0xA0</u></font>]
BreakoutGame -> HeadlessDisplay: <b>createysizeval9(133, 115, <font color="blue"><u>128</u></font>)</b>\n[<font color="red"><i>0x0A</i></font>, 0x85, 0x73, <font color="blue"><u>0x80</u></font>]
HeadlessDisplay -> BreakoutGame: <b>           displayReady_(16)</b>\n             [<font color="red"><i>0x01</i></font>, 0x10]
HeadlessDisplay -> BreakoutGame: <b>           displayReadyval8(204, 74)</b>\n           [<font color="red"><i>0x09</i></font>, 0xCC, 0x4A]
activate BreakoutGame
note over BreakoutGame, HeadlessDisplay: transition -> LAUNCH
BreakoutGame -> HeadlessDisplay: <b>clear_()</b>\n[<font color="red"><i>0x0C</i></font>, 0x71]
BreakoutGame -> HeadlessDisplay: <b>clearval1()</b>\n[<font color="red"><i>0x0D</i></font>, 0x44, 0xE3]
activate BreakoutGame
note over BreakoutGame, HeadlessDisplay: initColors()
BreakoutGame -> HeadlessDisplay: <b>setBGColorrb(6, <font color="blue"><u>53</u></font>, <font color="blue"><u>120</u></font>)</b>\n[<font color="red"><i>0x11</i></font>, 0x06, <font color="blue"><u>0x35</u></font>, <font color="blue"><u>0x78</u></font>]
BreakoutGame -> HeadlessDisplay: <b>setBGColorval5g(<font color="blue"><u>40</u></font>, 213, 218)</b>\n[<font color="red"><i>0x0F</i></font>, <font color="blue"><u>0x28</u></font>, 0xD5, 0xDA]
BreakoutGame -> HeadlessDisplay: <b>  setColorg(115, <font color="blue"><u>94</u></font>)</b>\n  [<font color="red"><i>0x12</i></font>, 0x73, <font color="blue"><u>0x5E</u></font>]
BreakoutGame -> HeadlessDisplay: <b>  setColorrbval7(<font color="blue"><u>174</u></font>, 67, 133, <font color="blue"><u>107</u></font>)</b>\n  [<font color="red"><i>0x00</i></font>, <font color="blue"><u>0xAE</u></font>, 0x43, 0x85, <font color="blue"><u>0x6B</u></font>]
deactivate BreakoutGame
...
@enduml